/* Regenerates the icon sprite in index.html from the real Lucide source.
   Run after adding an icon to MAP. Never hand-draw a path. */

import { readFileSync, writeFileSync } from "node:fs";

/* our sprite id -> lucide icon name */
const MAP = {
  dash:     "layout-dashboard",
  blocks:   "blocks",        // MCP tools are plugins, not electricity
  key:      "key-round",     // Providers is a credential store
  waypoints:"waypoints",     // Channels is distribution, not just a phone
  receipt:  "receipt",       // Usage & Billing
  info:     "info",          // an empty state is usually information
  warn:     "circle-alert",  // ...and only sometimes a problem
  server:   "server",
  book:     "book-open",
  zap:      "zap",
  bot:      "bot",
  phone:    "phone",
  inbox:    "inbox",
  radio:    "radio",
  users:    "users",
  card:     "credit-card",
  chart:    "chart-column",
  gear:     "settings",
  bell:     "bell",
  sun:      "sun",
  moon:     "moon",
  panel:    "panel-left-close",
  check:    "check",
  arrow:    "arrow-right",
  db:       "database",
  msg:      "message-circle",
  clock:    "clock",
  activity: "activity",
  sync:     "refresh-cw",
  globe:    "globe",
  plug:     "plug",
  plus:     "plus",
  search:   "search",
  alert:    "triangle-alert",
  dots:     "ellipsis",
  close:    "x",
  trash:    "trash-2",
  file:     "file-text",
};

const symbols = Object.entries(MAP).map(([id, name]) => {
  const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, "utf8");
  // Lucide ships width/height/stroke attrs on <svg>; we only want the geometry,
  // and stroke-width is controlled by our own .icon class.
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  return `    <symbol id="i-${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`;
});

/* The PXO brand mark. Not a Lucide icon — it carries its own fills and its own
   gradient, so it is defined here rather than pulled from the icon set.
   Square + "PX", then the violet ring that reads as the O. */
const PXO = `    <symbol id="i-pxo" viewBox="0 0 197 122">
      <linearGradient id="pxoGrad" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#5B2BE8"/>
        <stop offset="100%" stop-color="#C13BD2"/>
      </linearGradient>
      <rect width="122" height="122" rx="30" fill="url(#pxoGrad)"/>
      <text x="61" y="63" text-anchor="middle" dominant-baseline="central" fill="#ffffff"
            font-family="Manrope, ui-sans-serif, sans-serif" font-size="57" font-weight="800"
            letter-spacing="-2.5">PX</text>
      <circle cx="163" cy="61" r="27.5" fill="none" stroke="#6248E8" stroke-width="13"/>
    </symbol>`;

const sprite = `<svg width="0" height="0" style="position:absolute" aria-hidden="true">
  <!-- Lucide (ISC) + the PXO brand mark. Generated by build-icons.mjs — do not edit by hand. -->
  <defs>
${symbols.join("\n")}
${PXO}
  </defs>
</svg>`;

const html = readFileSync("index.html", "utf8");
const start = html.indexOf('<svg width="0"');
const end = html.indexOf("</svg>", start) + "</svg>".length;
if (start < 0) throw new Error("sprite block not found in index.html");

writeFileSync("index.html", html.slice(0, start) + sprite + html.slice(end));
console.log(`sprite rebuilt: ${symbols.length} icons from lucide-static`);
