/* Regenerates the icon sprite in index.html from the real Lucide source.
   Run after adding an icon to MAP. Never hand-draw a path. */

import { readFileSync, writeFileSync } from "node:fs";

/* our sprite id -> lucide icon name */
const MAP = {
  dash:     "layout-dashboard",
  book:     "book-open",
  zap:      "zap",
  bot:      "bot",
  phone:    "phone",
  inbox:    "inbox",
  radio:    "radio",
  users:    "users",
  card:     "credit-card",
  chart:    "chart-column",
  gear:     "settings",
  bell:     "bell",
  sun:      "sun",
  moon:     "moon",
  panel:    "panel-left-close",
  check:    "check",
  arrow:    "arrow-right",
  db:       "database",
  msg:      "message-circle",
  clock:    "clock",
  activity: "activity",
  sync:     "refresh-cw",
  globe:    "globe",
  plug:     "plug",
  plus:     "plus",
  search:   "search",
  alert:    "triangle-alert",
  dots:     "ellipsis",
  close:    "x",
  trash:    "trash-2",
  file:     "file-text",
};

const symbols = Object.entries(MAP).map(([id, name]) => {
  const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, "utf8");
  // Lucide ships width/height/stroke attrs on <svg>; we only want the geometry,
  // and stroke-width is controlled by our own .icon class.
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  return `    <symbol id="i-${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`;
});

const sprite = `<svg width="0" height="0" style="position:absolute" aria-hidden="true">
  <!-- Lucide (ISC). Generated by build-icons.mjs — do not edit by hand. -->
  <defs>
${symbols.join("\n")}
  </defs>
</svg>`;

const html = readFileSync("index.html", "utf8");
const start = html.indexOf('<svg width="0"');
const end = html.indexOf("</svg>", start) + "</svg>".length;
if (start < 0) throw new Error("sprite block not found in index.html");

writeFileSync("index.html", html.slice(0, start) + sprite + html.slice(end));
console.log(`sprite rebuilt: ${symbols.length} icons from lucide-static`);
